--- 
- hosts: Localhost
  become: yes
  tasks:
  - name: create ansible nodes
    ec2:
     key-name: myvpnkey
     instance_type: t2.micro
     image: ami-0b2a1c04de048dc86
     wait: yes
     region: us-east-2
     group: Ansible11may23
     count: 2
     vpc_subnet_id: subnet-09230291ce73f7c5a
     assign_public_ip: yes
     instance_tags:
        Name: Ansiblenodes