---
- hosts: 172.31.37.212
  become: yes
  tasks:
  - include: myfile.yml
  - name: i want to install my webserver
    apt:
     name: apache2
     state: present

  - name:  i want to copy index file to node side
    copy:
     src: myindexpage
     dest: /var/www/html/index.html
     
  - name: copy dyno files into nodes
    template:
     src: mydynoindex.j2
     dest: /var/www/html/index.html


  
