---
- hosts: 172.31.37.212
  become: yes
  vars:
   myvar01: git
   myvar02: tree
   myvar03: wget
  tasks:
   - name: i want display myvar01
     debug:
       msg: "{{myvar01}}"
    
   - name: i want to display myvar02
     debug:
        msg: "{{myvar02}}"

   - name: i want to display myvar03
     debug:
       msg: "{{myvar03}}"

     
