---
- hosts: mywebservers
  become: yes
  tasks:
  - name : i want to install git 
    apt:
     name: git
     state: present
    tags: my git

  - name: i want to install tree
    apt:
     name: tree
     state: present
    tags: my tree

  - name: i want to install wget
    apt:
     name: wget
     state: present
    tags: my wget
